### ISSUE TITLE
Abort/disconnect on call to Close()

### ISSUE THREAD

**Issue by martinhpedersen** [harenber/ptc-go#1]
Hi Torsten,

this package currently catches interrupt signals to implement abort/disconnect.
https://github.com/harenber/ptc-go/blob/master/ptc/pmodem.go#L331

A more idiomatic approach would be to allow for concurrent call to `Close()`, so that Pat (and other consumers) can communicate to the package that it should disconnect. This will also ensure that any application importing ptc-go can control the signal handling as they see fit.

Can we do without the signal handler in ptc-go?

**Comment by harenber** [comment]
@martinhpedersen  Yes.. think that should be perfectly doable.

**Comment by harenber** [comment]
Should have been fixed with https://github.com/harenber/ptc-go/commit/4b5a07a9c4db3b93038ed3196def683a083ca69c . I could still interrupt a data exchanged with the close() call coming in from Pat. My modem was even out of WA8DED mode.

**Comment by harenber** [comment]
During link setup, the Close() does not work properly.

**Comment by harenber** [comment]
This is sort-of-solved with https://github.com/harenber/ptc-go/commit/1d5fd225dac1841f69d726a9356cd7a442b37a44 The only "problem" remains that during link setup, Pat doesn't have the interface yet, hence it cannot send a Close() so you cannot interrupt during link setup yet. However, after a timeout everything should be catched normally. Once the connection is established, interrupt works (as far as I could test it).

**Comment by harenber** [comment]
Accidentally closed. Need to discuss with @martinhpedersen  how we handle the possibility to interrupt during link setup.

**Comment by blockmurder** [comment]
Still got some issues with abort/disconnect when DialURL() is called: https://github.com/la5nta/pat/blob/7e8460111ed96abf26197fb3b083f09780c8579d/exchange.go#L168  ```exchangeConn``` is nil during link setup and ```exchangeConn.Close()``` is not executed.
As soon as a connection is established, the the ```exchangeConn.Close()``` call works

@martinhpedersen could you have a look? My guess is that https://github.com/la5nta/pat/blob/7e8460111ed96abf26197fb3b083f09780c8579d/connect.go#L153 is the first to set ```exchangeConn = pModem```
Is this correct?

**Comment by martinhpedersen** [comment]
Yes, `func sessionExchange()` sets the global exchangeConn. I should really clean that up some how.. I don't like global vars like that.

Have a look here:
https://github.com/la5nta/pat/blob/7e8460111ed96abf26197fb3b083f09780c8579d/exchange.go#L193

 Both ARDOP and WINMOR have methods on the Modem/TNC struct that can be used to abort an ongoing dial. Maybe we can use the same approach for pactor?

**Comment by harenber** [comment]
Tested interrupting the call setup and traffic a couple of times with @blockmurder develop branch. All tests handled interrupts properly. Think this can be closed.

**Comment by harenber** [comment]
Reopened until merged into master (see #21)
