### ISSUE TITLE
Unabel to communicate with PTC modem (error: EOF)

### ISSUE THREAD

**Issue by blockmurder** [harenber/ptc-go#15]
Sometimes, after starting/restarting the PTC I'm not able to establish communication over the serial bus:
```
2019/01/05 19:27:49 QSY pactor: 7050.000
2019/01/05 19:27:52 Connecting to HB9AK (pactor)...
2019/01/05 19:27:53 Error while reading to the answer 636d643a20:EOF
2019/01/05 19:27:53 Unable to establish connection to remote: EOF
2019/01/05 19:27:54 QSX pactor: 10144.340
```
Only happens after start/restart of the modem. If this is the case, you can connect manually, e.g. with `minicom` and send "enter" which resolves the issue.

**Comment by harenber** [comment]
Fixed with https://github.com/harenber/ptc-go/pull/16
