### ISSUE TITLE
Default to MODE 0 (uncompressed transfer)

### ISSUE THREAD

**Issue by martinhpedersen** [harenber/ptc-go#19]
Ref [recent discussion](https://groups.google.com/d/msgid/pat-users/70eff718-47f6-d5d9-3473-5c99ee67718d%40gmail.com) regarding use of Pactor compression.

@harenber said:
> I completely agree. As the payload is already compressed by an
> open-sourced algorithm, the proprietary compression a) does not help and
> b) may raise legal issues.
> 
> The modem's default is to use "MODE 2" hence "auto-detect and compress
as needed". Binary (non 7bit-ASCII) data is not compressed.
> 
> At the moment, we do not change whatever is set in the PTC:
> 
> https://github.com/harenber/ptc-go/blob/develop/ptc/modem.go#L133-L136
> 
> Adding a "MODE 0" would switch the compression off and should be safe
for anyone. If a user wants it on purpose, he/she can use the
ptc_init_script (which is executed after the defaults).
>
> If nobody objects, will add that to the default init procedure.

I think we should do it, and aim to include the change in the next patch release of Pat (v0.7.1). This is especially important given WDT's ongoing struggles regarding the FCC petition RM-11831.

**Comment by blockmurder** [comment]
Pactor MOde is set to 0 during initialisation, every thing works as expected.

**Comment by blockmurder** [comment]
Reopen until merged into master (see #21)
