### ISSUE TITLE
Initialisation commands not executed when not in main menu (cmd:)

### ISSUE THREAD

**Issue by blockmurder** [harenber/ptc-go#20]
Pactor modem must be in main menu (cmd:) in order to execute the initialisation commands successfully.

Throws error message (unfortunately not captured) when for example in PACKET menu (pac:)
<pre>
2019/09/28 23:23:46 write: PTCH 31
<b>pac:</b> RROR: PSE TYPE HELPonse:
2019/09/28 23:23:46 write: MAXE 35
<b>pac:</b> RROR: PSE TYPE HELPonse:
</pre>

No error when in main menu (cmd:)
<pre>
2019/09/29 17:55:48 write: PTCH 31
<b>cmd:</b> ACTOR HOSTMODE CHANNEL: 31
2019/09/29 17:55:48 write: MAXE 35
<b>cmd:</b> IMEOUT-PARAMETER: 35nse: 
</pre>

ptc-go should make sure, main menu is active and abort on error.

**Comment by blockmurder** [comment]
Reopen until merged into master (see #21)

**Comment by harenber** [comment]
Tested with a PTC in different modes, code switches successfully to PACTOR (and even to PACKET if requested by the user)
