### ISSUE TITLE
Consider not closing issues until they are merged to master

### ISSUE THREAD

**Issue by martinhpedersen** [harenber/ptc-go#21]
Hi guys,

if you could change the workflow to only close issues once they have been merged to master, it would be easier to track changes that are ready to be pulled into Pat :)

I usually include a `Closes #142` in the end of a commit message when that commit resolves an issue. The pat repository is set up to only close the issue when such commits have been merged all the way to master. Maybe you could try the same approach here?

Just a though!

**Comment by martinhpedersen** [comment]
Looks like the `closes #142` behavior is default on github:
https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-the-same-repository

**Comment by blockmurder** [comment]
Makes sense to me. @harenber What do you think?
Still learning new features!

**Comment by harenber** [comment]
Yeah, make sense. How about tagging/marking those whose coding work is finished in develop and tested to work, so "only" waiting for merging? Something like "tested"? What do you think @martinhpedersen  @blockmurder  ?

**Comment by martinhpedersen** [comment]
Great! Thanks :D

A label for "tested" sounds like a good idea :)
