### ISSUE TITLE
Are current master ready for release?

### ISSUE THREAD

**Issue by martinhpedersen** [harenber/ptc-go#22]
https://github.com/harenber/ptc-go/commit/9f4402bb39779194861a3e404137d61290f7acc3

This is the latest commit on master. I may be forced to do an early release due to an ardop issue currently under investigation.

Are the current master (v2.0.1) tested and stable enough for release, or should I do a hotfix to include the ardop fix only? :)

**Comment by blockmurder** [comment]
I would prefer if we would do another release (2.0.2) with the little changes we made since 2.0.1 in order to get feedback on them as well. What do you think @harenber ?

**Comment by harenber** [comment]
You did all the work in v2 @blockmurder . So of course I agree.
