### ISSUE TITLE
Add support for Swiss-PTC modem

### ISSUE THREAD

**Issue by ClaudeMa** [harenber/ptc-go#26]
Swiss-PTC are pactor3 modem buid by SCHUEMPERLIN ENGINEERING AG under SCS licence
[http://www.schuemperlin.com/pages/ptc2a.htm](http://www.schuemperlin.com/pages/ptc2a.htm)
3 models exits Swiss-PTCa, Swiss-PTCII, Swiss-PTC-IIa
The Swiss-PTCII have less command then SCS-PTCII and no internal mailbox

supported command are

> ADdlf ANSwer BC BKchr CHeck CHOBell CHOchr CLr
> Connect CSDelay CTrlchr CWid CWSpeed CWTerm CWWeight DAte
> DELete DD DIR Discon ESCchr FEc GRP Help
> LFignore LIN LISt Listen LOg LOGIn LOCk MAXDown
> MAXError MAXSum MAXTry MAXUp MYcall MYSelc MOde MONitor
> NUL Phase PT PUblic QRTchr Read REMote RESEt
> RESTart SELFec Send SFile SHow SItor STatus SYStest
> Term TIme TR TXDelay Unproto Version Write
> 
> APower AQrg BRightn FSKAmpl MARk MYLevel PSKAmpl RLe
> SERBaud SPAce TOnes TRX UPDATE PACket Gate RCU
> HCr PTChn FAX USer PDuplex PDTimer TNC XUser
> FREE

Using this modem with Pat fail with error at initialisation

>     2020/02/20 18:41:24 Pactor initialization failed: Command "CM 0" not accepted:
>     *** ERROR: PSE TYPE HELP
> 
>     cmd:
 
in file "modem.go" removing command in bold from string "commands" solve the problem

> commands := []string{"MYcall " + p.localAddr, "PTCH " + strconv.Itoa(PactorChannel),
> "MAXE 35", **"CM 0"**, "REM 0", **"BOX 0"**, **"MAIL 0**", "CHOB 0", **"UML 1"**,
> "TONES 4", "MARK 1600", "SPACE 1400", "CWID 0", "CONType 3", "MODE 0"}

**Comment by harenber** [comment]
Hi,

wow.. I wasn't aware that those devices exist. Thanks for reporting it.

I suggest that we should try to identify the devices and send init strings accordingly. Could you send the welcome message of your Swiss device (or any other command+answer you are aware of that would help to differentiate between a Swiss-PTC from a SCS-PTC)? That would be very helpful.

  Torsten

**Comment by blockmurder** [comment]
@harenber 
I just had a look at the manual. All of the commands mentioned except for **CM** are beeing set to their default value. **CM 0** only disables the connect text. As far as I can recall, the driver does not bother if connect text is enabled. 
Therefore we could consider removing the mentioned commands from the initialisation routine in order to keep the driver as simple as possible.

**Comment by ClaudeMa** [comment]
hi harenber

Welcome message is

> PTC-II System  68360/DSP-56156
>     Version V.3.3j  Level 3
>   (C) 2003  SCS GmbH & Co. KG 
> 
> 524288 bytes SRAM detected
> 
> Packet Radio Port 1: NO MODEM detected
> 
> BIOS: Version 1.81 detected 
> 
> FLASHCALL: CICR-L3
> 
> *** STBY >> 
> 
> cmd: 
> 

the Version command give

> PTC-II - High Performance HF/VHF/UHF Communications Controller
> PACTOR - Level-III - High Speed Data Transfer Protocol
> Version V.3.3j (C) 1994-2003  Schuemperlin Engineering AG - Switzerland
> 
> *** HOST FIRMWARE ***
> 
> BIOS: Version 1.81 detected 
> 
> Packet Radio Port 1: NO MODEM detected
> 
> LICENSED TO: Schuemperlin Engineering
> 
> cmd: 
>

**Comment by harenber** [comment]
@blockmurder Thanks for looking that up. I also had no problem connecting without these commands. I think I just gonna wipe them out, so with the next version, the swiss modem should just work (tm) :-)

**Comment by ghost** [comment]
Hi,

I've been doing some successful tests with this family of modems and the firmware I have seems to support all the commands that were reported as problematic, for the record:

Welcome message
```
PTC-II System  68360/DSP-56156
    Version V.4.1p  Level 3
  (C) 2016  SCS GmbH & Co. KG 

524288 bytes SRAM detected

Packet Radio Port 1: NO MODEM detected

BIOS: Version 1.81 detected 

FLASHCALL: *SCSPTC*

*** STBY >> 
```

Supported commands
```
Command key words:                                                              
==================                                                              
ACheck    ADdlf     Amtor     ARX       BAKup     BAUdot    BEll      BC        
BKchr     BOOT      Box       CHeck     CHOBell   CHOchr    CLr       CMsg      
Connect   CSDelay   CTExt     CTrlchr   CWid      CWMoni    CWSpeed   CWTerm    
CWWeight  CYcle     DAte      DELete    DD        DIR       Discon    ESCchr    
FEc       Help      LFignore  LIN       LIst      Listen    LOg       LOGIn     
LOCk      MAil      MAXDown   MAXError  MAXSum    MAXTry    MAXUp     MYcall    
MYSelc    MOde      MONitor   NUL       Phase     PT        Qrt       QRTChr    
Read      RELOad    REMote    RESEt     RESTart   Send      SFile     SHow      
SQuelch   STatus    SYStest   Term      TIme      TOnes     TR        TXDelay   
UMlauts   Unproto   USOs      VERIfy    Version   Write                         
                                                                                
APower    AQrg      AUdio     BRightn   FSKAmpl   MARk      MYLevel   PSKAmpl   
RLe       SERBaud   SPAce     TRX       UPDATE    PACket    Gate      RCU       
HCr       PTChn     FAX       BMsg      USer      PDuplex   PDTimer   XUser     
TNC       PSKTerm   NAVtex    FREE      ANSwer    LICENSE   CONType   POSition  
EQualize                                                                        
                                                                                
For more information type: Help <CMD> (eg: H Help)                              
```

Version Info
```
PTC-II - High Performance HF/VHF/UHF Communications Controller                  
PACTOR - Level-III - High Speed Data Transfer Protocol                          
 >>> Professional / Marine Firmware V.4.1p <<<                                  
 (C) 1994-2016  SCS GmbH & Co. KG - Germany                                     
                                                                                
*** TINY FIRMWARE VERSION ***                                                   
                                                                                
BIOS: Version 1.81 detected                                                     
                                                                                
Packet Radio Port 1: NO MODEM detected   
```

Best regards,

**Comment by harenber** [comment]
Closing as issue was resolved https://github.com/harenber/ptc-go/commit/05bf3bfa31ef8a8bd7c067abc995db69bffd0e7d
