### ISSUE TITLE
Query regarding ptc-go src

### ISSUE THREAD

**Issue by guitarpicva** [harenber/ptc-go#27]
Hello again harenber, 

Thanks again for producing this module for pat.  It has released Winlink and my PTC modem from the jaws of Windows.  It is greatly appreciated.  

I was wondering if you would mind if I picked through your code in an attempt to do something similar for the Node Red platform, as well as to create direct "terminal" access to the PTC modems.  One thing sorely lacking in Pactor-land is a nice ad hoc chat and infrastructure-less message transfer program combined into one UI.  I have a great deal of experience along those lines and I think it is a natural fit for this ARQ modem.  

Go is pretty similar to most languages I use so I am sure I can figure out the syntax in short order.  The ancient and mostly un-needed serial protocol is the most annoying part, and I want to encapsulate that and surround it with a more modern TCP socket approach with an ASCII command set.  This allows it to be sort of an appliance that can be used by various programs in a much simpler manner.

I know it is open source, but I thought it at least polite to ask your permission. :)

Regards,
Mitch
AB4MW

**Comment by harenber** [comment]
Hi Mitch,

the current version of the code is contributed by @blockmurder . Maybe he can/should comment.

What I am concernd, I am a friend of open-source, so I would be happy if any code would be re-used elsewhere. 

BTW: I use node red myself for my complete home automation ( https://hub.docker.com/r/harenber/rpinodered-gruenbeck ).

73s

 Torsten DL1THM

**Comment by guitarpicva** [comment]
Torsten,

I will await input from @blockmurder as well then.  Thank you.  

Node Red is an obvious choice for this sort of serially controlled device.  It also lends itself well to being able to have control of the device remotely from inaccessible sites, or on non-Amateur radio systems which is my primary target.  I have built controllers for other commercially available modem devices in Node Red already.

Regards,
Mitch

**Comment by blockmurder** [comment]
@guitarpicva Sorry for the delayed response.
As mentioned in #28 @harenber will probably soon add a LICENCE file stating this software is licenced under MIT Licence

I like the idea of open-source so I'd love to see this code or parts of it being used in other open-source projects :-D

Cheers
Matthias

**Comment by harenber** [comment]
License added, so I think we can close this one here.
