### ISSUE TITLE
ptc-go doesn't have a license

### ISSUE THREAD

**Issue by taowa** [harenber/ptc-go#28]
Hello,

I'm trying to package this plugin in Debian, but I can't seem to find a LICENSE.md or any copyright notices. The closest I've found is #27, but unfortunately that's not explicit enough to use as a license. @martinhpedersen, @harenber, @blockmurder, can you please pick a license together then reply here (and if you can, send an email to 956547@bugs.debian.org) stating that you license your previous contributions under that license? Can you also add a LICENSE.md for future contributions? For reference, [here's a list of licenses that are compatible with the Debian Free Software Guidelines](https://wiki.debian.org/DFSGLicenses).

Thanks!
Taowa Munene-Tardif
taowa@debian.org

**Comment by harenber** [comment]
I would suggest to take the same as the Pat main code (MIT License). @martinhpedersen , @blockmurder  would you be ok with it? If yes, I would add a license file to this repository.

**Comment by martinhpedersen** [comment]
The MIT License is preferrable if you ask me :) :+1:

**Comment by blockmurder** [comment]
@harenber Sorry for the delay.
I'm fine with the MIT License

**Comment by taowa** [comment]
Thanks!

**Comment by taowa** [comment]
(@blockmurder )
