### ISSUE TITLE
You've (partially) changed the package name

### ISSUE THREAD

**Issue by martinhpedersen** [harenber/ptc-go#30]
Hi Torsten,

https://github.com/harenber/ptc-go/commit/7a52b606e8ee0bce1ce5500900821c2bdebc27de

This commit changes the last component of the import path, which should be named the same as the package name.

Also, by changing the import path you've effectivly broken compatibility with code expecting the old path.

I suggest that you revert this çommit and keep the pactor namespace :)

**Comment by harenber** [comment]
Hi @martinhpedersen,

thanks for pointing me to that. Well.. in the past, the directory was called "ptc" while the package was "pactor", which was.. well.. historically grown. 

I'll revert that and rename the directory to "pactor", so it matches the package name.

**Comment by harenber** [comment]
should be fixed with https://github.com/harenber/ptc-go/commit/bb52ee2d80d0c79bcb9ac1f3f55d5201dc681201

**Comment by martinhpedersen** [comment]
Ah, I see :)

Looks very good now :+1:
