### ISSUE TITLE
Feaure Request: Control Radio via PTC

### ISSUE THREAD

**Issue by DC7IA** [harenber/ptc-go#31]
The PACTOR controllers can control radios using the TRX control port.

This can be done using the "TRX" command, which has a syntax that is quite simple. Documentation can be found in the manual.

Example:

Set the radio type to Yaesu with 9600 Baud: `trx type y 9600`
Set frequency: `trx freq 7050.5`

We really only need two commands, one for setting the radio (can be done using an initalisation command) and then the other to set the new frequency.

So there should be a way to specify the frequency in pat, then have it set by ptc-go.

Would be great if pat/ptc-go could do that. :D

**Comment by harenber** [comment]
Please read the README.md, it's already on the TODO list (although I have little time at the moment). Feel free to contribute with a pull request.

Closing here.
