### ISSUE TITLE
Avoid logging by default

### ISSUE THREAD

**Issue by martinhpedersen** [harenber/ptc-go#4]
It would be great if we could get rid of all log output from ptc-go. It is considered best practice not to write anything to stdout/stderr from a library be default.

I realize that some of the log output could be useful for debugging purposes, so maybe you should consider having an environment variable control the debug logging? In the winmor and ardop packages, I've implemented this with success. They do not log by default, but I have the option to enable it at runtime by setting the environment variables `winmor_debug=1`/`ardop_debug=1`.

https://github.com/la5nta/wl2k-go/blob/master/transport/winmor/winmor.go#L64

If a fatal error occurs, it is common to return an error describing the problem to the application. That way, the user may be informed of any error without relying on the library itself to communicate directly to the user. This is especially important for Pat, as the user may not be interfacing with the application through the terminal (web GUI users).

**Comment by harenber** [comment]
Hi @martinhpedersen , thanks for your valuable reviews and comments. 

With https://github.com/harenber/ptc-go/commit/4a56a2bed457c19059c36a4598f002c9daf91a75 there should be no logging anymore if not an environment variable is set (as you suggested). Added information in the README.md. Have a nice evening!
